### ISSUE TITLE
rgdal and maptools will retire soon

### ISSUE THREAD

**Issue by edzer** [eliaskrainski/INLAspacetime#2]
Hi Elias, this seems to be a new CRAN package - please note that we're in the process of retiring packages `rgdal`, `maptools` and `rgeos`; see https://r-spatial.org/r/2022/04/12/evolution.html and https://r-spatial.org/r/2022/12/14/evolution2.html; a third blog post is upcoming. Let me know if you need help replacing functions of these packages.

Cc: @rsbivand

**Comment by rsbivand** [comment]
Will CMD check with evolution status 2L and without retiring packages on the library path later today and report back. Properly conditioned use of suggested but archived packages isn't a big problem, but will be hard to maintain.

**Comment by eliaskrainski** [comment]
Hi Edzer and Roger, I managed to avoid this dependency. I managed with the rnaturalearth plus either sp or sf packages. Thanks!

**Comment by eliaskrainski** [comment]
However, it is only in the github version for now. Will be in CRAN in near future.

**Comment by edzer** [comment]
Great, thanks!

**Comment by rsbivand** [comment]
[00check.log](https://github.com/eliaskrainski/INLAspacetime/files/11170843/00check.log)
is OK for 0.1.5, with:
```
* checking package dependencies ... NOTE
Packages suggested but not available for checking: 'maptools', 'rgdal'
```
